### ISSUE TITLE
Autodocumentation for context supplied arguments

### ISSUE THREAD

**Issue by mundya** [project-rig/rig#75]
@mossblaser said:

> I'd also like it if the use named contextual arguments could update the function signature too for auto-documentation purposes.

Modifying the function signature seems like a Very Bad<sup>TM</sup> / difficult thing to do.  My proposal would be to modify the docstring by automagically adding in the context kwargs.

Any thoughts?

**Comment by mossblaser** [comment]
In recent times, the documentation for the MachineController has been missing function signatures which is a real pain in the backside. I think this is due to RTD using python 2 to build (when building with Python 3, things are still buggy...).

In my opinion, given the number of "expected" arguments in many functions which don't warrant documenting (e.g. 'x', 'y' etc) but which are currently unlisted, this is a fairly severe bug. I'll try and look into this a little more seriously.

**Comment by mossblaser** [comment]
Apparently you can [prefix docstrings with function signatures](http://sphinx-doc.org/ext/autodoc.html#confval-autodoc_docstring_signature) so with any luck I can build something which does this!
